### ISSUE TITLE
Add a test runner for the holiday definitions

### ISSUE THREAD

**Issue by iGEL** [holidays/definitions#118]
I think it would be useful to run the tests defined in the definitions in this repository together with the rspec test suite. It would enable the authors to easily test their definitions and would also make the result visible in the PRs.

This probably requires to copy quite some code from the holidays gem, but I think it'll be worth it.

**Comment by ppeble** [comment]
This is an excellent idea! We do have an issue for this specific thing but looking at it now I can see how it's not really clear to someone who is not deeply invested already in these repos. 😄 

The other issue is https://github.com/holidays/definitions/issues/42. Once I get back from my trip (and get over my jet lag) I will look into this again and figure out how I want to combine these two and make them more clear.

The other issue: https://github.com/holidays/definitions/issues/42

**Comment by iGEL** [comment]
Ah, sorry. I should have checked.

**Comment by ppeble** [comment]
It's okay! I am glad you did this because it shows that I should get my head back into it. I thought that I was the main person looking for it so it's nice to know that someone else also thinks it's a good thing for us to invest our time in. 😄
