### ISSUE TITLE
RO region outdated

### ISSUE THREAD

**Issue by ste26054** [holidays/definitions#126]
Hello, 

This is regarding public holidays in Romania.
According to:
- https://en.wikipedia.org/wiki/Public_holidays_in_Romania
- https://zilelibere.com/zilelibere2019.html

Some Bank holidays were added. Below are when they will fall in 2019: 

- 2019 January 24 - Day of Unification of the Romanian Principalities (From 2017) (https://www.mediafax.ro/politic/legea-prin-care-24-ianuarie-a-fost-declarata-zi-libera-nelucratoare-a-fost-promulgata-de-iohannis-15777292)
- 2019 April 26 - Good Friday (From 2018) (https://www.mediafax.ro/social/iohannis-a-promulgat-legea-prin-care-vinerea-mare-este-sarbatoare-legala-nelucratoare-17058413)
- 2019 June 1 - Children's Day (From 2017) (https://www.avocatnet.ro/articol_43954/Din-2017-salaria%C8%9Bii-vor-sta-acas%C4%83-%C8%99i-de-Ziua-Copilului-1-iunie-inclus%C4%83-de-azi-pe-lista-liberelor-legale.html)

I am okay to do a merge request with the changes, I am just unsure about the Orthodox Good Friday. Is there an existing helper method for that?

Best regards

**Comment by ppeble** [comment]
Hi @ste26054, sorry for the delay! A new PR with the proposed changes would be perfect if you are willing!

In regards to your question about Orthodox Good Friday, we do have a method for `orthodox_easter` that we generally use to calculate Good Friday. In general terms we use Easter as a signpost to determine holidays based around easter (like Good Friday). You can read [here in our SYNTAX guide](https://github.com/holidays/definitions/blob/master/doc/SYNTAX.md#pre-existing-methods) for an example for Good Friday in the US. 

Additionally, here is a link to an [example for Good Friday for Georgian holidays](https://github.com/holidays/definitions/blob/master/ge.yaml#L11-L14). I think you can most likely do the same thing for the `:ro` definitions.

Let me know if you run into any issues producing the PR and feel free to request my review once it is open. Thank you!

**Comment by ste26054** [comment]
PR done, but I have divergent test results with Travis: https://github.com/holidays/definitions/pull/131#issuecomment-471623310

**Comment by ppeble** [comment]
Closing this since the [PR addressing it](https://github.com/holidays/definitions/pull/131) has been merged. This update will be included in the upcoming v5.0.0 definitions and v8.0.0 of the ruby gem. Thank you!
