### ISSUE TITLE
Some US holiday issues

### ISSUE THREAD

**Issue by ghiculescu** [holidays/definitions#134]
Hey @ppeble our fork is way out of sync with this. We need to merge it upstream, but in the meantime, thought you might want these changes: https://github.com/TandaHQ/definitions/pull/4

**Comment by ppeble** [comment]
Cool, thank you for this! I will pull these changes in before the next major version bump, which will hopefully be out within the next two weeks.

**Comment by ppeble** [comment]
These commits are now merged. Thanks!
