### ISSUE TITLE
Wrong indentation in de.yaml

### ISSUE THREAD

**Issue by DERNTOAN** [holidays/definitions#147]
Hey guys,

the indentation for `Internationaler Frauentag` seems to be wrong.
See [here](https://github.com/holidays/definitions/blob/master/de.yaml#L87)

Thanks for the great gem!

**Comment by ttwo32** [comment]
Oh...
I will modify it later.
Please wait.
Thank you. :)

**Comment by estani** [comment]
It still looks wrong though it's not an issue (it's proper yaml).
I'm adding a PR for a new German Holiday in Berlin, I'll fix it there.

**Comment by ttwo32** [comment]
@estani @DERNTOAN Sorry for the lazy response.
@estani  I have merged your [PR](https://github.com/holidays/definitions/pull/149) . Thanks!! :)
