### ISSUE TITLE
de_by_aux is incorrect.

### ISSUE THREAD

**Issue by chinito** [holidays/definitions#15]
I tried to fix something here on de_by_aux.
Which, in my opinion is Holidays in Augsburg, which is in Bavaria.
So, all holidays in Bavaria should be in de_by_aux plus Friedensfest on the 8th of August.

When doing:
```
Holidays.between(Date.today.beginning_of_year, Date.today.end_of_year, :de_by).length
```
result is 13, correct!

When doing:
```
Holidays.between(Date.today.beginning_of_year, Date.today.end_of_year, :de_by).length
``` 
result is 10, incorrect!

Turns out Allerheiligen, Mariä Himmelfahrt and Fronleichnam are missing.

Additionally I discoverd :de_sn_aux and :de_th_aux. I guess this should be DE Schleswig-Holstein Augsburg and DE Thüringen Augsburg. Both things don't exist. So I don't get it, please explain and I'll help to improve this. Thanks

**Comment by ptrimble** [comment]
Thank you for the issue! That is indeed strange! Not sure what is happening but it does indeed look wrong. I will look at this and get back to you.

**Comment by chinito** [comment]
Thanks, can you clear up what  :de_sn_aux and :de_th_aux should be? I have really no idea. 
The only thing I know is, there is a local center of a small town called Schwesing (about 1000 inhabitants) in the north of Germany, but they don't have this holiday.
Also :de_th_aux looks totally strange to me. Only the City of Augsburg located in Bavaria has this special holiday. And it's so awesome that your gem now supports this, because me and my company are located in Augsburg :)

**Comment by chinito** [comment]
So, if found a first issue, but it's on the holidays/holidays repo. So I'm doing an issue there
