### ISSUE TITLE
de_by Issue on Mariä Himmelfahrt 15th of august

### ISSUE THREAD

**Issue by chinito** [holidays/definitions#17]
As stated in the bavarian law and also on wikipedia. The 15th of august is only a holiday in bavarian counties (Gemeinden) with a majority of catholics compared to the protestants. So if there will be 80% not catholic or protestant, but 11% catholic vs. 9% protestant, it'll still be a holiday.
This is checked all 4 to 5 years by the bavarian statistics agency. Find attached a map of where this is a holiday, blue states holiday, white no holiday.

https://www.statistik.bayern.de/medien/presse/221_2016_44_a_himmelfahrt_karte.pdf

**Comment by klyonrad** [comment]
So this issue can be closed then?

**Comment by ppeble** [comment]
@klyonrad Yes! Thank you for reminding me, I simply missed closing this after the PR was merged.
