### ISSUE TITLE
CODE_OF_CONDUCT.md, referenced in CONTRIBUTING.md, is missing in the repository

### ISSUE THREAD

**Issue by jensberke** [holidays/definitions#94]
CONTRIBUTING.md references a file called "CODE_OF_CONDUCT.md" in the "Code of Conduct" section, but the file is missing in the repository.

**Comment by ppeble** [comment]
Thank you! This was missed when I split the definitions into their own directory. I will fix it tonight. 👍

**Comment by ppeble** [comment]
Fixed! Thank you!
